version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mkdocs-material
    versions:
    - 6.2.6
    - 6.2.7
    - 6.2.8
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.6
    - 7.1.0
    - 7.1.1
    - 7.1.2
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: flake8-pytest-style
    versions:
    - 1.4.0
  - dependency-name: orjson
    versions:
    - 3.5.0
    - 3.5.1
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: pylint
    versions:
    - 2.7.1
    - 2.7.2
  - dependency-name: pydantic
    versions:
    - 1.7.3
    - "1.8"
  - dependency-name: aiohttp
    versions:
    - 3.7.4
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: safety
    versions:
    - 1.10.3
  - dependency-name: plotly
    versions:
    - 4.14.3
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
  - dependency-name: git-changelog
    versions:
    - 0.4.2
